version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks:
      apinetwork:
        ipv4_address: 172.53.0.10
    command: sleep infinity

networks:
  apinetwork:
    ipam:
      config:
        - subnet: 172.53.0.0/16
